// Copyright (C) 2012 Angel Hernández Matos / Bonafide Ideas.
// You can redistribute this software and/or modify it under the terms of the 
// Microsoft Reciprocal License (Ms-RL).  This program is distributed in the hope 
// that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
// See License.txt for more details. 

/* C++ compiler      : Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.40219.01 for 80x86
   Creation date     : 14/04/2012
   Developer         : Angel Hernández Matos
   e-m@il            : angel@bonafideideas.com 
 					 : angeljesus14@hotmail.com
   Website           : http://www.bonafideideas.com
*/

// File generated by Wsutil Compiler version 1.0092 
#include "stdafx.h"
#include <WebServices.h>
#include "cybernanny3.xsd.h"

typedef struct _cybernanny3_xsdLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct // StringBuilder
        {
            WS_FIELD_DESCRIPTION FactoryType;
            WS_FIELD_DESCRIPTION _any;
            WS_FIELD_DESCRIPTION* StringBuilderFields [2]; 
        } StringBuilderdescs; // end of StringBuilder
    } globalTypes;  // end of global types
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING StringBuilderTypeName;  // StringBuilder
            WS_XML_STRING StringBuilderTypeNamespace;  // http://schemas.datacontract.org/2004/07/System.Text
            WS_XML_STRING StringBuilderFactoryTypeLocalName;  // FactoryType
            WS_XML_STRING StringBuilderFactoryTypeNamespace;  // http://schemas.microsoft.com/2003/10/Serialization/
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _cybernanny3_xsdLocalDefinitions;

const static _cybernanny3_xsdLocalDefinitions cybernanny3_xsdLocalDefinitions =
{
    { // global types
        0,
        {   // StringBuilder
            { // field description for FactoryType
            WS_ATTRIBUTE_FIELD_MAPPING,
            (WS_XML_STRING*)&cybernanny3_xsdLocalDefinitions.dictionary.xmlStrings.StringBuilderFactoryTypeLocalName, // FactoryType
            (WS_XML_STRING*)&cybernanny3_xsdLocalDefinitions.dictionary.xmlStrings.StringBuilderFactoryTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_XML_QNAME_TYPE,
            0,
            WsOffsetOf(StringBuilder, FactoryType),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for FactoryType
            { // field description for _any
            WS_ANY_CONTENT_FIELD_MAPPING,
            0,
            0,
            WS_XML_BUFFER_TYPE,
            0,
            WsOffsetOf(StringBuilder, _any),
            0,
            0,
            0xffffffff
            },    // end of field description for _any
            {    // fields description for StringBuilder
            (WS_FIELD_DESCRIPTION*)&cybernanny3_xsdLocalDefinitions.globalTypes.StringBuilderdescs.FactoryType,
            (WS_FIELD_DESCRIPTION*)&cybernanny3_xsdLocalDefinitions.globalTypes.StringBuilderdescs._any,
            },
        },    // StringBuilder
    }, // end of global types
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("StringBuilder",&cybernanny3_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/System.Text",&cybernanny3_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("FactoryType",&cybernanny3_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.microsoft.com/2003/10/Serialization/",&cybernanny3_xsdLocalDefinitions.dictionary.dict, 3),
        },  // end of xmlStrings
        
        {   // cybernanny3_xsddictionary
        // f7142761-a446-426a-b058-6e25b9cee83b 
        { 0xf7142761, 0xa446, 0x426a, { 0xb0, 0x58, 0x6e,0x25, 0xb9, 0xce, 0xe8, 0x3b } },
        (WS_XML_STRING*)&cybernanny3_xsdLocalDefinitions.dictionary.xmlStrings,
        4,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of cybernanny3_xsdLocalDefinitions

const _cybernanny3_xsd cybernanny3_xsd =
{
    {// globalTypes
        {
        sizeof(StringBuilder),
        __alignof(StringBuilder),
        (WS_FIELD_DESCRIPTION**)&cybernanny3_xsdLocalDefinitions.globalTypes.StringBuilderdescs.StringBuilderFields,
        WsCountOf(cybernanny3_xsdLocalDefinitions.globalTypes.StringBuilderdescs.StringBuilderFields),
        (WS_XML_STRING*)&cybernanny3_xsdLocalDefinitions.dictionary.xmlStrings.StringBuilderTypeName, // StringBuilder
        (WS_XML_STRING*)&cybernanny3_xsdLocalDefinitions.dictionary.xmlStrings.StringBuilderTypeNamespace, // http://schemas.datacontract.org/2004/07/System.Text
        0,
        0,
        0,
        },   // end of struct description for StringBuilder
    }, // globalTypes
    {// globalElements
        {
            (WS_XML_STRING*)&cybernanny3_xsdLocalDefinitions.dictionary.xmlStrings.StringBuilderTypeName, // StringBuilder
            (WS_XML_STRING*)&cybernanny3_xsdLocalDefinitions.dictionary.xmlStrings.StringBuilderTypeNamespace, // http://schemas.datacontract.org/2004/07/System.Text
            WS_STRUCT_TYPE,
            (void*)&cybernanny3_xsd.globalTypes.StringBuilder,
        },
    }, // globalElements
}; // end of _cybernanny3_xsd
