// Copyright (C) 2012 Angel Hernández Matos / Bonafide Ideas.
// You can redistribute this software and/or modify it under the terms of the 
// Microsoft Reciprocal License (Ms-RL).  This program is distributed in the hope 
// that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
// See License.txt for more details. 

/* C++ compiler      : Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.40219.01 for 80x86
   Creation date     : 14/04/2012
   Developer         : Angel Hernández Matos
   e-m@il            : angel@bonafideideas.com 
 					 : angeljesus14@hotmail.com
   Website           : http://www.bonafideideas.com
*/

// File generated by Wsutil Compiler version 1.0092 
#include "stdafx.h"
#include <WebServices.h>
#include "cybernanny1.xsd.h"

typedef struct _cybernanny1_xsdLocalDefinitions 
{
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING FactoryTypeTypeName;  // FactoryType
            WS_XML_STRING FactoryTypeTypeNamespace;  // http://schemas.microsoft.com/2003/10/Serialization/
            WS_XML_STRING IdTypeName;  // Id
            WS_XML_STRING RefTypeName;  // Ref
            WS_XML_STRING anyTypeTypeName;  // anyType
            WS_XML_STRING anyURITypeName;  // anyURI
            WS_XML_STRING base64BinaryTypeName;  // base64Binary
            WS_XML_STRING BooleanTypeName;  // boolean
            WS_XML_STRING ByteTypeName;  // byte
            WS_XML_STRING dateTimeTypeName;  // dateTime
            WS_XML_STRING DecimalTypeName;  // decimal
            WS_XML_STRING DoubleTypeName;  // double
            WS_XML_STRING FloatTypeName;  // float
            WS_XML_STRING IntTypeName;  // int
            WS_XML_STRING LongTypeName;  // long
            WS_XML_STRING QNameTypeName;  // QName
            WS_XML_STRING ShortTypeName;  // short
            WS_XML_STRING StringTypeName;  // string
            WS_XML_STRING unsignedByteTypeName;  // unsignedByte
            WS_XML_STRING unsignedIntTypeName;  // unsignedInt
            WS_XML_STRING unsignedLongTypeName;  // unsignedLong
            WS_XML_STRING unsignedShortTypeName;  // unsignedShort
            WS_XML_STRING CharTypeName;  // char
            WS_XML_STRING durationTypeName;  // duration
            WS_XML_STRING guidTypeName;  // guid
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _cybernanny1_xsdLocalDefinitions;

const static _cybernanny1_xsdLocalDefinitions cybernanny1_xsdLocalDefinitions =
{
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("FactoryType",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.microsoft.com/2003/10/Serialization/",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("Id",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("Ref",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("anyType",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("anyURI",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("base64Binary",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("boolean",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("byte",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("dateTime",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("decimal",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("double",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("float",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("int",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("long",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("QName",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("short",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("string",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("unsignedByte",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("unsignedInt",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("unsignedLong",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("unsignedShort",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("char",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("duration",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 23),
            WS_XML_STRING_DICTIONARY_VALUE("guid",&cybernanny1_xsdLocalDefinitions.dictionary.dict, 24),
        },  // end of xmlStrings
        
        {   // cybernanny1_xsddictionary
        // fb15b0b1-692b-44bf-b4c7-86c644987583 
        { 0xfb15b0b1, 0x692b, 0x44bf, { 0xb4, 0xc7, 0x86,0xc6, 0x44, 0x98, 0x75, 0x83 } },
        (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings,
        25,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of cybernanny1_xsdLocalDefinitions

const _cybernanny1_xsd cybernanny1_xsd =
{
    {// globalAttributes
        { //  FactoryType
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeName, // FactoryType
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_XML_QNAME_TYPE,
        }, //  end of FactoryType
        { //  Id
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.IdTypeName, // Id
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_STRING_TYPE,
        }, //  end of Id
        { //  Ref
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.RefTypeName, // Ref
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_STRING_TYPE,
        }, //  end of Ref
    }, // globalAttributes
    {// globalElements
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.anyTypeTypeName, // anyType
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_XML_BUFFER_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.anyURITypeName, // anyURI
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_STRING_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.base64BinaryTypeName, // base64Binary
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_BYTES_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.BooleanTypeName, // boolean
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_BOOL_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.ByteTypeName, // byte
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_INT8_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.dateTimeTypeName, // dateTime
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_DATETIME_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.DecimalTypeName, // decimal
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_DECIMAL_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.DoubleTypeName, // double
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_DOUBLE_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FloatTypeName, // float
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_FLOAT_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.IntTypeName, // int
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_INT32_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.LongTypeName, // long
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_INT64_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.QNameTypeName, // QName
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_XML_QNAME_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.ShortTypeName, // short
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_INT16_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.StringTypeName, // string
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_STRING_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.unsignedByteTypeName, // unsignedByte
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_UINT8_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.unsignedIntTypeName, // unsignedInt
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_UINT32_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.unsignedLongTypeName, // unsignedLong
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_UINT64_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.unsignedShortTypeName, // unsignedShort
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_UINT16_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.CharTypeName, // char
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_INT32_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.durationTypeName, // duration
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_DURATION_TYPE,
        },
        {
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.guidTypeName, // guid
            (WS_XML_STRING*)&cybernanny1_xsdLocalDefinitions.dictionary.xmlStrings.FactoryTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/
            WS_GUID_TYPE,
        },
    }, // globalElements
}; // end of _cybernanny1_xsd
