// Copyright (C) 2012 Angel Hernández Matos / Bonafide Ideas.
// You can redistribute this software and/or modify it under the terms of the 
// Microsoft Reciprocal License (Ms-RL).  This program is distributed in the hope 
// that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
// See License.txt for more details. 

/* C++ compiler      : Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.40219.01 for 80x86
   Creation date     : 14/04/2012
   Developer         : Angel Hernández Matos
   e-m@il            : angel@bonafideideas.com 
 					 : angeljesus14@hotmail.com
   Website           : http://www.bonafideideas.com
*/

// File generated by Wsutil Compiler version 1.0092 
#include "stdafx.h"
#include <WebServices.h>
#include "cybernanny2.xsd.h"

typedef struct _cybernanny2_xsdLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct {  //  Common_RequestType
            WS_ENUM_VALUE Common_RequestTypeValues[2];
            unsigned long nameIndices[2];
        } Common_RequestTypeenumDesc; // end of Common_RequestType
    } globalTypes;  // end of global types
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING Common_RequestTypeRecordVideo;  // RecordVideo
            WS_XML_STRING Common_RequestTypeTakePicture;  // TakePicture
            WS_XML_STRING Common_RequestTypeTypeName;  // Common.RequestType
            WS_XML_STRING Common_RequestTypeTypeNamespace;  // http://schemas.datacontract.org/2004/07/CyberNanny_webRole
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _cybernanny2_xsdLocalDefinitions;

const static _cybernanny2_xsdLocalDefinitions cybernanny2_xsdLocalDefinitions =
{
    { // global types
        0,
        { // Common_RequestType
            { //  WS_ENUM_VALUE
                {
                0, 
                (WS_XML_STRING*)&cybernanny2_xsdLocalDefinitions.dictionary.xmlStrings.Common_RequestTypeRecordVideo, // RecordVideo
                },
                {
                1, 
                (WS_XML_STRING*)&cybernanny2_xsdLocalDefinitions.dictionary.xmlStrings.Common_RequestTypeTakePicture, // TakePicture
                },
            }, //  WS_ENUM_VALUE
            {  0,  1,},  // nameIndices
        }, //Common_RequestType
    }, // end of global types
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("RecordVideo",&cybernanny2_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("TakePicture",&cybernanny2_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("Common.RequestType",&cybernanny2_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/CyberNanny_webRole",&cybernanny2_xsdLocalDefinitions.dictionary.dict, 3),
        },  // end of xmlStrings
        
        {   // cybernanny2_xsddictionary
        // 08a40ded-2e65-43cb-a018-a37cf8b8f8f1 
        { 0x08a40ded, 0x2e65, 0x43cb, { 0xa0, 0x18, 0xa3,0x7c, 0xf8, 0xb8, 0xf8, 0xf1 } },
        (WS_XML_STRING*)&cybernanny2_xsdLocalDefinitions.dictionary.xmlStrings,
        4,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of cybernanny2_xsdLocalDefinitions

const _cybernanny2_xsd cybernanny2_xsd =
{
    {// globalTypes
        { //  Common_RequestType
            (WS_ENUM_VALUE *)&cybernanny2_xsdLocalDefinitions.globalTypes.Common_RequestTypeenumDesc.Common_RequestTypeValues,
            2,
            11,
            (unsigned long *)&cybernanny2_xsdLocalDefinitions.globalTypes.Common_RequestTypeenumDesc.nameIndices,
        }, //  end of Common_RequestType
    }, // globalTypes
    {// globalElements
        {
            (WS_XML_STRING*)&cybernanny2_xsdLocalDefinitions.dictionary.xmlStrings.Common_RequestTypeTypeName, // Common.RequestType
            (WS_XML_STRING*)&cybernanny2_xsdLocalDefinitions.dictionary.xmlStrings.Common_RequestTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/CyberNanny_webRole
            WS_ENUM_TYPE,
            (WS_ENUM_DESCRIPTION*)&cybernanny2_xsd.globalTypes.Common_RequestType,
        },
    }, // globalElements
}; // end of _cybernanny2_xsd
